server {
    listen 80;
    server_name karimasyari.com www.karimasyari.com api.ks-backend.cloud admin.ks-backend.cloud auth.ks-backend.cloud;

    # Halaman sementara/test
    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
